name: "mlops-plugin"
description: "Links each commit to its MLflow run, renders a Summary report, and records results in a Gist CSV ledger."
inputs:
  mlflow_tracking_uri:
    description: "MLflow tracking URI (e.g., DagsHub MLflow)"
    required: true
  mlflow_token:
    description: "Token for MLflow/DagsHub"
    required: true
  gist_id:
    description: "Gist ID to store commitHistory.csv"
    required: false
  gist_token:
    description: "Token with gist scope (passed from workflow)"
    required: false
  gist_filename:
    description: "filename in the Gist (default commitHistory.csv)"
    required: false
    default: "commitHistory.csv"
  use_gomlops:
    description: "Optional: use external GoMLOps detector"
    required: false
    default: "false"
  gomlops_version:
    description: "Optional: GoMLOps version/commit"
    required: false
    default: "latest"
  trained_this_run:
    description: "Set true if the job trained a new model this run"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python deps
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas matplotlib requests

    # pull the latest CSV from Gist so append works on top
    - name: (Gist) Pull existing CSV
      if: ${{ inputs.gist_id != '' }}
      shell: bash
      env:
        GIST_ID:       ${{ inputs.gist_id }}
        GIST_FILENAME: ${{ inputs.gist_filename }}
        GIST_TOKEN:    ${{ inputs.gist_token }}
      run: |
        set -euo pipefail
        echo "Fetching $GIST_FILENAME from gist:$GIST_ID (if present)..."
        if [ -z "${GIST_TOKEN:-}" ]; then
          echo "No gist_token provided; cannot read a secret Gist. Continuing without prefetch."
          exit 0
        fi
        RESP=$(curl -sS -H "Authorization: Bearer ${GIST_TOKEN}" "https://api.github.com/gists/${GIST_ID}")
        FILE_NAME=$(jq -r --arg fn "$GIST_FILENAME" '.files[$fn].filename // empty' <<<"$RESP")
        if [ -n "$FILE_NAME" ]; then
          jq -r --arg fn "$GIST_FILENAME" '.files[$fn].content' <<<"$RESP" > commitHistory.csv || true
          echo "Pulled $GIST_FILENAME from Gist."
        else
          echo "File $GIST_FILENAME not found in Gist; will create it on push."
        fi

    - name: Detect cause (Data/Script/None)
      shell: bash
      run: |
        echo "Repo root contents:" && ls -la
        echo ".github/scripts contents:" && ls -la .github/scripts || true

        if [ -f ".github/scripts/detect_cause_mlops.sh" ]; then
          chmod +x .github/scripts/detect_cause_mlops.sh || true
          bash .github/scripts/detect_cause_mlops.sh
        else
          echo "::warning:: .github/scripts/detect_cause_mlops.sh not found; defaulting CAUSE_MLOPS=None"
          echo "CAUSE_MLOPS=None" >> "$GITHUB_ENV"
        fi

    - name: Extract MLflow metrics/params/version
      id: mlflow
      shell: bash
      env:
        MLFLOW_TRACKING_URI: ${{ inputs.mlflow_tracking_uri }}
        MLFLOW_TOKEN: ${{ inputs.mlflow_token }}
        TRAINED_THIS_RUN: ${{ inputs.trained_this_run }}
      run: |
        python .github/scripts/extract_mlflow.py

    - name: Render val_accuracy chart
      shell: bash
      run: |
        python .github/scripts/render_val_accuracy_svg.py || true

    - name: Generate Summary markdown
      shell: bash
      run: |
        python "${{ github.action_path }}/../.github/scripts/generate_summary_md.py" > "$RUNNER_TEMP/summary.md"
        echo "mlops summary" >> "$GITHUB_STEP_SUMMARY"
        cat "$RUNNER_TEMP/summary.md" >> "$GITHUB_STEP_SUMMARY"

    - name: Append to commitHistory.csv (local)
      shell: bash
      env:
        TRAINED: ${{ inputs.trained_this_run }}
        # pass-through of outputs written by extract_mlflow.py
        ACCURACY: ${{ steps.mlflow.outputs.accuracy }}
        LOSS: ${{ steps.mlflow.outputs.loss }}
        VAL_ACCURACY: ${{ steps.mlflow.outputs.val_accuracy }}
        VAL_LOSS: ${{ steps.mlflow.outputs.val_loss }}
        TRAIN_DUR: ${{ steps.mlflow.outputs.training_duration }}
        MODEL_VERSION: ${{ steps.mlflow.outputs.model_version }}
        EPOCHS: ${{ steps.mlflow.outputs.epochs }}
        OPT_NAME: ${{ steps.mlflow.outputs.opt_name }}
        OPT_LR: ${{ steps.mlflow.outputs.opt_lr }}
        MONITOR: ${{ steps.mlflow.outputs.monitor }}
        PATIENCE: ${{ steps.mlflow.outputs.patience }}
        RESTORE_BEST_WEIGHTS: ${{ steps.mlflow.outputs.restore_best_weights }}
        RUN_ID: ${{ steps.mlflow.outputs.run_id }}
      run: |
        python .github/scripts/append_commitHistory.py

    - name: (Gist) Push CSV to Gist
      if: ${{ inputs.gist_id != '' }}
      shell: bash
      env:
        GIST_ID:       ${{ inputs.gist_id }}
        GIST_FILENAME: ${{ inputs.gist_filename }}
        GIST_TOKEN:    ${{ inputs.gist_token }}
      run: |
        set -euo pipefail
        if [ -z "${GIST_TOKEN:-}" ]; then
          echo "::error::gist_token input missing. Pass secrets.GIST_TOKEN from the workflow."; exit 1
        fi
        if [ ! -s commitHistory.csv ]; then
          echo "::error::commitHistory.csv not found/empty before push."; exit 1
        fi
        payload=$(jq -n --arg fn "$GIST_FILENAME" --rawfile content commitHistory.csv '{files: {($fn): {content: $content}}}')
        curl -sS -X PATCH \
          -H "Authorization: Bearer ${GIST_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "$payload" \
          "https://api.github.com/gists/${GIST_ID}" >/dev/null
        echo "Gist updated: $GIST_FILENAME"

    - name: Post Summary
      shell: bash
      run: |
        echo "### MLOps Summary" >> $GITHUB_STEP_SUMMARY
        cat SUMMARY.md >> $GITHUB_STEP_SUMMARY

    - name: (Optional) Prune old MLflow runs
      if: ${{ inputs.trained_this_run == 'true' }}
      shell: bash
      env:
        MLFLOW_TRACKING_URI: ${{ inputs.mlflow_tracking_uri }}
        MLFLOW_TOKEN: ${{ inputs.mlflow_token }}
      run: |
        python .github/scripts/prune_mlflow_runs.py || true
