name: "mlops-plugin"
description: "Links each commit to its MLflow run, renders a Summary report, and records results in a Gist CSV ledger."
inputs:
  mlflow_tracking_uri:
    description: "MLflow tracking URI (e.g., DagsHub MLflow)"
    required: true
  mlflow_token:
    description: "Token for MLflow/DagsHub"
    required: true
  gist_id:
    description: "Gist ID to store commitHistory.csv"
    required: false
  gist_token:
    description: "Token with gist scope (passed from workflow)"
    required: false
  gist_filename:
    description: "filename in the Gist (default commitHistory.csv)"
    required: false
    default: "commitHistory.csv"
  use_gomlops:
    description: "Optional: use external GoMLOps detector"
    required: false
    default: "false"
  gomlops_version:
    description: "Optional: GoMLOps version/commit"
    required: false
    default: "latest"
  trained_this_run:
    description: "Set true if the job trained a new model this run"
    required: false
    default: "false"
  train:
    description: "Run MLproject training in the caller workspace"
    required: false
    default: "true"
  mlproject_entrypoint:
    description: "MLproject entry point"
    required: false
    default: "main"
  env_manager:
    description: "MLflow env manager (local|virtualenv|conda)"
    required: false
    default: "local"
  mlflow_username:
    description: "MLflow username (optional for DagsHub)"
    required: false
    default: ""
  install_mlflow:
    description: "pip install mlflow before training"
    required: false
    default: "true"
    
runs:
  using: "composite"
  steps:

    - name: Init TRAINED_THIS_RUN
      shell: bash
      run: echo "TRAINED_THIS_RUN=false" >> "$GITHUB_ENV"
    
    - name: Detect cause (Data/Script/Both/None)
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/../.github/scripts/detect_cause_mlops.sh"
        "${{ github.action_path }}/../.github/scripts/detect_cause_mlops.sh"
        echo "Detected CAUSE_MLOPS=$CAUSE_MLOPS"

    - name: Ensure MLflow is installed
      if: ${{ inputs.install_mlflow != 'false' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "mlflow>=2.4"
      

    - name: Train with MLflow (caller repo)
      if: ${{ (inputs.train == 'true' || (inputs.train != 'false' && env.CAUSE_MLOPS != 'None')) && hashFiles('MLproject') != '' }}
      shell: bash
      env:
        MLFLOW_TRACKING_URI:       ${{ inputs.mlflow_tracking_uri }}
        MLFLOW_TRACKING_USERNAME:  ${{ inputs.mlflow_username }}
        MLFLOW_TRACKING_PASSWORD:  ${{ inputs.mlflow_token }}
      run: |
        mlflow run . -e "${{ inputs.mlproject_entrypoint }}" --env-manager="${{ inputs.env_manager }}"
        echo "TRAINED_THIS_RUN=true" >> "$GITHUB_ENV"
    

    - name: Extract MLflow info
      id: ml
      shell: bash
      env:
        MLFLOW_TRACKING_URI: ${{ inputs.mlflow_tracking_uri }}
        MLFLOW_TOKEN: ${{ inputs.mlflow_token }}
        TRAINED_THIS_RUN: ${{ inputs.trained_this_run }}
      run: |
          python "${{ github.action_path }}/../.github/scripts/extract_mlflow.py"


    # 6) Append one row, then sort by timestamp ASC (no prepend)
    - name: Append commitHistory.csv
      shell: bash
      env:
        TRAINED_THIS_RUN: ${{ env.TRAINED_THIS_RUN }}
      run: python "${{ github.action_path }}/../.github/scripts/append_commitHistory.py"

    # 7) (Optional) Push updated CSV back to Gist
    - name: (Gist) Push updated CSV
      if: ${{ inputs.gist_id != '' && inputs.gist_token != '' }}
      shell: bash
      run: python "${{ github.action_path }}/../.github/scripts/append_commitHistory.py" --push-gist

    # 8) Render chart (tolerant if CSV empty)
    - name: Render val_accuracy chart
      shell: bash
      run: python "${{ github.action_path }}/../.github/scripts/render_val_accuracy_svg.py" || true

    # 9) Generate Summary (caller repo Job Summary)
    - name: Generate Summary (Job Summary)
      shell: bash
      run: |
        python "${{ github.action_path }}/../.github/scripts/generate_summary_md.py" > "$RUNNER_TEMP/summary.md"
        cat "$RUNNER_TEMP/summary.md" >> "$GITHUB_STEP_SUMMARY"