name: devops-mlops-report (caller)

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  report:
    permissions:
      actions: read
      contents: read
    uses: cyndi-s/devops-mlops-report/.github/workflows/ci-report.yml@report-v2
    with:
      config_path: report-config.yml
    secrets:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
